module BasicStrategy
  HARD = {
    '4': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::HIT,
      '5': Actions::HIT,
      '6': Actions::HIT,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '5': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::HIT,
      '5': Actions::HIT,
      '6': Actions::HIT,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '6': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::HIT,
      '5': Actions::HIT,
      '6': Actions::HIT,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '7': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::HIT,
      '5': Actions::HIT,
      '6': Actions::HIT,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '8': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::HIT,
      '5': Actions::HIT,
      '6': Actions::HIT,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '9': {
      '2': Actions::HIT,
      '3': Actions::DOUBLE,
      '4': Actions::DOUBLE,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '10': {
      '2': Actions::DOUBLE,
      '3': Actions::DOUBLE,
      '4': Actions::DOUBLE,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::DOUBLE,
      '8': Actions::DOUBLE,
      '9': Actions::DOUBLE,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '11': {
      '2': Actions::DOUBLE,
      '3': Actions::DOUBLE,
      '4': Actions::DOUBLE,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::DOUBLE,
      '8': Actions::DOUBLE,
      '9': Actions::DOUBLE,
      '10': Actions::DOUBLE,
      '1': Actions::HIT
    },
    '12': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '13': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '14': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '15': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '16': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '17': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::STAY,
      '10': Actions::STAY,
      '1': Actions::STAY
    },
    '18': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::STAY,
      '10': Actions::STAY,
      '1': Actions::STAY
    },
    '19': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::STAY,
      '10': Actions::STAY,
      '1': Actions::STAY
    },
    '20': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::STAY,
      '10': Actions::STAY,
      '1': Actions::STAY
    },
    '21': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::STAY,
      '10': Actions::STAY,
      '1': Actions::STAY
    }
  }

  SOFT = {
    '12': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::HIT,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '13': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::HIT,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '14': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::HIT,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '15': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::DOUBLE,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '16': {
      '2': Actions::HIT,
      '3': Actions::HIT,
      '4': Actions::DOUBLE,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '17': {
      '2': Actions::HIT,
      '3': Actions::DOUBLE,
      '4': Actions::DOUBLE,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::HIT,
      '8': Actions::HIT,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '18': {
      '2': Actions::STAY,
      '3': Actions::DOUBLE,
      '4': Actions::DOUBLE,
      '5': Actions::DOUBLE,
      '6': Actions::DOUBLE,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::HIT,
      '10': Actions::HIT,
      '1': Actions::HIT
    },
    '19': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::STAY,
      '10': Actions::STAY,
      '1': Actions::STAY
    },
    '20': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::STAY,
      '10': Actions::STAY,
      '1': Actions::STAY
    },
    '21': {
      '2': Actions::STAY,
      '3': Actions::STAY,
      '4': Actions::STAY,
      '5': Actions::STAY,
      '6': Actions::STAY,
      '7': Actions::STAY,
      '8': Actions::STAY,
      '9': Actions::STAY,
      '10': Actions::STAY,
      '1': Actions::STAY
    }
  }

  PAIRS = {
    '4': {
      '2': true,
      '3': true,
      '4': true,
      '5': true,
      '6': true,
      '7': true,
      '8': false,
      '9': false,
      '10': false,
      '1': false
    },
    '6': {
      '2': true,
      '3': true,
      '4': true,
      '5': true,
      '6': true,
      '7': true,
      '8': false,
      '9': false,
      '10': false,
      '1': false
    },
    '8': {
      '2': false,
      '3': false,
      '4': false,
      '5': true,
      '6': true,
      '7': false,
      '8': false,
      '9': false,
      '10': false,
      '1': false
    },
    '10': {
      '2': false,
      '3': false,
      '4': false,
      '5': false,
      '6': false,
      '7': false,
      '8': false,
      '9': false,
      '10': false,
      '1': false
    },
    '12': {
      '2': true,
      '3': true,
      '4': true,
      '5': true,
      '6': true,
      '7': false,
      '8': false,
      '9': false,
      '10': false,
      '1': false
    },
    '14': {
      '2': true,
      '3': true,
      '4': true,
      '5': true,
      '6': true,
      '7': true,
      '8': false,
      '9': false,
      '10': false,
      '1': false
    },
    '16': {
      '2': true,
      '3': true,
      '4': true,
      '5': true,
      '6': true,
      '7': true,
      '8': true,
      '9': true,
      '10': true,
      '1': true
    },
    '18': {
      '2': true,
      '3': true,
      '4': true,
      '5': true,
      '6': true,
      '7': false,
      '8': true,
      '9': true,
      '10': false,
      '1': false
    },
    '20': {
      '2': false,
      '3': false,
      '4': false,
      '5': false,
      '6': false,
      '7': false,
      '8': false,
      '9': false,
      '10': false,
      '1': false
    },
    '2': {
      '2': true,
      '3': true,
      '4': true,
      '5': true,
      '6': true,
      '7': true,
      '8': true,
      '9': true,
      '10': true,
      '1': true
    }
  }
end